# optional since v1.27.0
version: "3.9"
services:
  coj-backend:
    image: ghcr.io/caribbean-online-judge/coj.web:master
    ports:
      - "5001:5001"
    environment:
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - SMTP_HOST=$SMTP_HOST
      - SMTP_PASSWORD=$SMTP_PASSWORD
      - SMTP_PORT=$SMTP_PORT
      - SMTP_USERNAME=$SMTP_USERNAME
      - SMTP_FROM=$SMTP_FROM
      - JWT_SECRET=$JWT_SECRET
